### ISSUE TITLE
缺少pkl

### ISSUE THREAD

**Issue by TowerPro** [foamliu/Joint-Estimation-of-Age-and-Gender#7]
发生报错FileNotFoundError: [Errno 2] No such file or directory: 'data/imdb-gender-age101.pkl'
请问哪里可以下载？

**Comment by zhedahe** [comment]
> 
> 
> 发生报错FileNotFoundError: [Errno 2] No such file or directory: 'data/imdb-gender-age101.pkl'
> 请问哪里可以下载？

你百度搜索： imdb 数据集，会有相关的下载链接，只需两个压缩包：imdb_crop.tar 以及 imdb_meta.tar ，在该项目的目录下新建data文件夹，将2个tar目录放入其中，然后顺着教程来即可，即运行python pre_process.py 结束后自动在data目录下生产pkl文件。

**Comment by snowyrain** [comment]
> > 发生报错FileNotFoundError: [Errno 2] No such file or directory: 'data/imdb-gender-age101.pkl'
> > 请问哪里可以下载？
> 
> 你百度搜索： imdb 数据集，会有相关的下载链接，只需两个压缩包：imdb_crop.tar 以及 imdb_meta.tar ，在该项目的目录下新建data文件夹，将2个tar目录放入其中，然后顺着教程来即可，即运行python pre_process.py 结束后自动在data目录下生产pkl文件。

请问imdb.mat怎么生成呢，感谢！

**Comment by zhedahe** [comment]
抱歉，我刚看到。
因为有段时间没做相关领域的研究和测试了，我需要重新check再回复你。
另外，从我的测试看这个repo结果并不让人满意，可能和数据集主要是老外面孔有关。相对而言，我后面参考了飞浆的：https://github.com/WhiteFireFox/paddle-age-predict，结果还可以，希望对你有帮助。


发自我的iPhone

**Comment by zhedahe** [comment]
抱歉，近期有事刚看到。很久没搞这个项目了，你说的细节我需要重新review，关于这个repo我评估测试看，效果达不到预期，可能跟数据集的分布主要是欧美人居多有关，且婴幼儿误识别概率较大。
如果对开发库没有要求，推荐我上个月参考的仓库，是百度飞桨的：https://github.com/WhiteFireFox/paddle-age-predict
如果有问题我们再沟通，祝好！













在 2021-11-18 12:11:18，"ZXY" ***@***.***> 写道：

发生报错FileNotFoundError: [Errno 2] No such file or directory: 'data/imdb-gender-age101.pkl'
请问哪里可以下载？

你百度搜索： imdb 数据集，会有相关的下载链接，只需两个压缩包：imdb_crop.tar 以及 imdb_meta.tar ，在该项目的目录下新建data文件夹，将2个tar目录放入其中，然后顺着教程来即可，即运行python pre_process.py 结束后自动在data目录下生产pkl文件。

请问imdb.mat怎么生成呢，感谢！

**Comment by Rzzzj** [comment]
我运行训练文件时会报下面这个错误
C:\Users\86153\anaconda3\envs\pytorch_gpu_cpu\python.exe E:\Age-and-Gender-master\train.py 
C:\Users\86153\anaconda3\envs\pytorch_gpu_cpu\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")
Traceback (most recent call last):
  File "E:\Age-and-Gender-master\train.py", line 235, in <module>
    main()
  File "E:\Age-and-Gender-master\train.py", line 231, in main
    train_net(args)
  File "E:\Age-and-Gender-master\train.py", line 63, in train_net
    pin_memory=True)
  File "C:\Users\86153\anaconda3\envs\pytorch_gpu_cpu\lib\site-packages\torch\utils\data\dataloader.py", line 347, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "C:\Users\86153\anaconda3\envs\pytorch_gpu_cpu\lib\site-packages\torch\utils\data\sampler.py", line 108, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

Process finished with exit code 1
我想问一下是问一下怎么修改
